services:
  - type: web
    name: election-predictor
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ELECTION_PREDICTOR_NEON_DATABASE_URL
        sync: false
      - key: ELECTION_PREDICTOR_OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
